#!/bin/sh

set -e

xcodebuild \
-workspace Example/SSAppURLsExample.xcworkspace \
-scheme SSAppURLsExample \
-sdk iphonesimulator \
clean build \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
